export const companies = [
  'Microsoft',
  'Apple',
  'Google',
  'Adobe',
  'Salesforce',
  'Oracle',
  'SAP',
  'Intuit',
  'VMware',
  'Symantec',
  'Samsung',
  'Intel',
  'AMD',
  'Nvidia',
  'Lenovo',
  'Dell',
  'HP',
  'Asus',
  'Acer',
  'Facebook',
  'Twitter',
  'LinkedIn',
  'Snap Inc.',
  'Pinterest',
  'Reddit',
  'TikTok',
  'Instagram',
  'Amazon',
  'Alibaba',
  'eBay',
  'Shopify',
  'Walmart',
  'JD.com',
  'Flipkart',
  'PayPal',
  'Rakuten',
  'MercadoLibre',
  'AT&T',
  'Verizon',
  'T-Mobile',
  'Vodafone',
  'China Mobile',
  'NTT',
  'Telefónica',
  'SoftBank',
  'Deutsche Telekom',
  'Orange S.A.',
  'Amazon Web Services (AWS)',
  'Microsoft Azure',
  'Google Cloud Platform (GCP)',
  'IBM Cloud',
  'Salesforce',
  'Oracle Cloud',
  'Alibaba Cloud',
  'VMware Cloud',
  'Rackspace',
  'DigitalOcean',
  'Intel',
  'Taiwan Semiconductor Manufacturing Company (TSMC)',
  'Nvidia',
  'Samsung Electronics',
  'Broadcom',
  'Qualcomm',
  'Micron Technology',
  'Advanced Micro Devices (AMD)',
  'Texas Instruments',
  'Applied Materials'
];
