export const roles = [
  'Software Engineer',
  'Web Developer',
  'Mobile App Developer',
  'Game Developer',
  'DevOps Engineer',
  'Quality Assurance Engineer',
  'Systems Analyst',
  'Database Administrator',
  'UI/UX Designer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Embedded Systems Developer',
  'Cloud Engineer',
  'Machine Learning Engineer',
  'Blockchain Developer',
  'AR/VR Developer',
  'IT Specialist',
  'Network Engineer',
  'Systems Administrator',
  'IT Manager',
  'Cybersecurity Analyst',
  'Data Analyst',
  'IT Support Specialist',
  'IT Consultant',
  'Cloud Architect',
  'Network Administrator',
  'Information Security Analyst',
  'Database Developer',
  'IT Auditor',
  'Chief Information Officer (CIO)',
  'Data Scientist',
  'Data Engineer',
  'Business Intelligence Analyst',
  'Quantitative Analyst',
  'Data Architect',
  'Statistician',
  'Big Data Engineer',
  'AI Engineer',
  'Ethical Hacker',
  'Security Engineer',
  'Penetration Tester',
  'Security Consultant',
  'Chief Information Security Officer (CISO)',
  'Security Architect',
  'Incident Responder',
  'Security Auditor',
  'Electrical Engineer',
  'Hardware Engineer',
  'Computer Engineer',
  'Firmware Engineer',
  'ASIC Design Engineer',
  'PCB Designer',
  'Embedded Systems Engineer',
  'Technology Director',
  'Chief Technology Officer (CTO)',
  'Project Manager',
  'Product Manager',
  'Technical Lead',
  'Scrum Master',
  'Tech Writer',
  'Technical Trainer',
  'UI/UX Researcher',
  'Tech Recruiter',
  'IT Sales Professional',
  'Tech Entrepreneur',
  'Systems Integrator',
  'Technology Evangelist'
];
